language: go
sudo: required
dist: trusty
os:
- linux
addons:
  apt:
    packages:
    - fuse
    - libfuse-dev
    - pkg-config
    - upx-ucl
    - glusterfs-client
services:
  - docker
go:
  - "1.9"
  - "1.10"
  - "tip"

before_install:
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo modprobe fuse ; sudo chmod 666 /dev/fuse ; sudo chown root:$USER /etc/fuse.conf ; fi
  - if [[ $TRAVIS_OS_NAME == osx ]]; then brew update && brew tap caskroom/cask && brew cask install osxfuse ; fi
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

install:
  - make deps

script:
  - make lint
  - make build
  - make test-unit
#  - sudo -E bash -c 'eval "$(gimme $TRAVIS_GO_VERSION)" && make test'
#  - sudo ls -lah /var/log/glusterfs/
#  - sudo cat /var/log/glusterfs/*
  - ./docker-volume-gluster

after_success:
  - sudo --preserve-env bash c 'eval "$(gimme $TRAVIS_GO_VERSION)" && make test-coverage'

before_deploy:
  - make release
  - docker --version
  - make docker-plugin
  - PLUGIN_TAG=$(git describe --tags --abbrev=0) make docker-plugin
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - make docker-plugin-push
  - PLUGIN_TAG=$(git describe --tags --abbrev=0) make docker-plugin-push

deploy:
  provider: releases
  api_key:
    secure: SAD6luuJhgzS7ZavymCxLaTlCbxp9VQax0uf4ozWByt0uwsLKtDM4Je4c9z9bx40PmEBKOpSoso4umL4AcY1yrQ2UTMJD+GxedmqDnge2ibfhHZMTxeDkLF3JLsACfQmibNzN/+b9nNdgyzQYnB4+OvKOmEvtHWwNP7qOuU+9QTNK/rNt5MBXk29aJFL1/t3oIvCfHl1D96pssE6uVURcXiPGkgNcSLBUewYwPwqjGqgG/xu/lgQEwpW6AE4OfwJLpdGMR/V1DUNMNs47Gt7Vh+PBRm/M7cZUYyc+CRuXuSM+PKr9xlH8mFHu6IrcM4n5Sy94A7ldB5dfn9HA+WLXEOhSej3NB06sFkjITnKSWCVCGVzzXuH5CMiwBDRKmhFLunFe9Wcz52W2wIumesaNuZOm9LbiBV47UicggeiZkhar1tvjQoFgw6R57+Wxdhdon7fwVO3euRSH7fm0RyEN1PgO92U5/gHgOO+Khlsl3GPqWNgyqeh0Ej4Ke9mFB0VjO+a8uNAQlrp+v94kQSWqpXUD30/fnZhu+sBURJ1pikH/WAhcnKEvYk7Kq5/kSuYqO0dxxEDrHh00Gwo/uHhhnOp3BNe/v1/TseSS4FOxaLrbTKCDRU+B38bsi8FoZ7J68xK9dT19TF+6ZXqka1LNIyV4ITCjkRenHMfCWWrF78=
  file_glob: true
  file:
    - build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
    go: "1.10"
    condition: $TRAVIS_OS_NAME == linux && $TRAVIS_PULL_REQUEST == false
